### ISSUE TITLE
Verify parameter

### ISSUE THREAD

**Issue by Bachboi** [GearPlug/sugarcrm-python#10]
Hi. 
Can you change client.py line 56 

"return self._parse(client.post(self.url + endpoint, data=data, verify=True, **kwargs))"

to 

"return self._parse(client.post(self.url + endpoint, data=data, verify=self.verify, **kwargs))"

Verify is defaulted to True in Client constructor, but should be passed if set to False.

**Comment by gustav0** [comment]
This has been fixed. Thanks for your reporting it!
