### ISSUE TITLE
Seems to not work with LDAP

### ISSUE THREAD

**Issue by AlixANNERAUD** [GearPlug/sugarcrm-python#13]
Hello,
Thank you for your project. However, I am having problems with authentication. During authentication, sugar returns "Error: 1012. Message LDAP Authentication failed but supplied password was already encrypted". I have the impression that LDAP authentication is not implemented in the library. I am using Sugar CRM 6.5.24 (CRM Suite 7.8.6). Here is the script in question: 
```
from sugarcrm.client import Client

client = Client('******', '*******', '*****************************')

result = client.search_by_module('SEARCH_STRING', 'first_name', 'John')


print(result)
```

**Comment by ingmferrer** [comment]
Hello,

In fact, this library does not support LDAP. Sorry.

Any PR is welcome.
