### ISSUE TITLE
Was Closed.. no answer..

### ISSUE THREAD

**Issue by Zooarcher** [GearPlug/sugarcrm-python#14]
You requested,
Without the stack trace of the exception we are unable to help you.,

I provided what I had, which isnt much more then this.
Code:
```
from sugarcrm.client import Client

client = Client('https://sugar.***.com/', '****', '****')
client.get_available_modules('MODULE_NAME')
print(client)
```

Exception has occurred: TypeError
string indices must be integers
  File "/home/sugar/test1/sugartesting.py", line 3, in <module>
    client = Client('https://sugar.***.com/', '***', '***')
TypeError: string indices must be integers

**Comment by ingmferrer** [comment]
try this:
```

from sugarcrm.client import Client

client = Client('https://sugar.***.com/', '****', '****')
client.get_available_modules()
print(client)
```
