### ISSUE TITLE
set_entry issue

### ISSUE THREAD

**Issue by lmorroni** [GearPlug/sugarcrm-python#3]
Hello,
I am trying to use your wrapper to update my SuiteCRM accounts.  I am having issues with the set_entry call.  Here's my code to simply loop through all accounts and rename them all to the same thing.

````
crm_all_accounts = crm.get_entry_list("Accounts",max_results=100000,query="bt_id_c != ''")
for a in crm_all_accounts['entry_list']:
        account = a['name_value_list']
        account['name']['value'] = "MY NEW NAME";
        crm.set_entry("Accounts",account)
````

When I run this, it destroys the Account data.  It adds Arrays into the address field and blanks out the name field.  Am I using this wrapper wrong?
Thanks,
Larry

**Comment by ingmferrer** [comment]
Hello there,

I would say you are using wrong the wrapper. What you need to do is send a dict in set_entry method with the account id and the field or fields that you want to update.

I tested with my Leads so my code looks something like this:
```
crm_all_leads = c.get_entry_list("Leads", max_results=100)
for lead in crm_all_leads['entry_list']:
    r = c.set_entry('Leads', {'id': lead['id'], 'first_name': 'New First Name''})
```

As you can see I updated 'first_name' and everything else is intact.

Regards.

**Comment by lmorroni** [comment]
Thanks, Miguel.  I was passing in the entire dict that I was getting back from the entry_list.  The approach you outlined above works for me.  Much appreciated.
Larry
